export default [
  "software",
  "software development",
  "programming",
  "coding",
  "IT",
  "Information Technology",
  "Tutorial",
  "Schooling",
  "development",
  "just do it",
  "jdit",
  "marc philippe beaujean",
  "marc beaujean",
  "marc",
  "mark",
  "justdoit",
  "justdoIT",
]
